# Generated by Django 3.1.5 on 2021-09-03 19:31

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositMemberCurrent',
            fields=[
                ('deposit_member_current_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deposit_member_current_user_related', models.CharField(editable=False, max_length=255)),
                ('deposit_member_current_transaction_related', models.CharField(editable=False, max_length=255)),
                ('deposit_member_current_amount', models.DecimalField(decimal_places=12, default=0, editable=False, max_digits=30)),
                ('deposit_member_current_total_profit_share', models.DecimalField(decimal_places=12, default=0, editable=False, max_digits=30)),
                ('deposit_member_current_period_base', models.IntegerField(default=0, editable=False)),
                ('deposit_member_current_period_left', models.IntegerField(default=0, editable=False)),
                ('deposit_member_current_finished_status', models.BooleanField()),
                ('deposit_member_current_created_by', models.CharField(editable=False, max_length=255)),
                ('deposit_member_current_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-deposit_member_current_id',),
            },
        ),
        migrations.CreateModel(
            name='DepositMemberMandatory',
            fields=[
                ('deposit_member_mandatory_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deposit_member_mandatory_user_related', models.CharField(editable=False, max_length=255)),
                ('deposit_member_mandatory_amount', models.DecimalField(decimal_places=12, default=0, editable=False, max_digits=30)),
                ('deposit_member_mandatory_period_left', models.IntegerField(default=0, editable=False)),
                ('deposit_member_mandatory_period_end', models.DateTimeField(editable=False, null=True)),
                ('deposit_member_mandatory_created_by', models.CharField(editable=False, max_length=255)),
                ('deposit_member_mandatory_created_date', models.DateTimeField(auto_now_add=True)),
                ('deposit_member_mandatory_updated_by', models.CharField(editable=False, max_length=255)),
                ('deposit_member_mandatory_updated_date', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ('-deposit_member_mandatory_user_related',),
            },
        ),
        migrations.CreateModel(
            name='DepositMemberPrincipal',
            fields=[
                ('deposit_member_principal_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deposit_member_principal_user_related', models.CharField(editable=False, max_length=255)),
                ('deposit_member_principal_payment_principal_status', models.BooleanField(default=False, editable=False)),
                ('deposit_member_principal_payment_principal_amount', models.DecimalField(decimal_places=12, default=0, editable=False, max_digits=30)),
                ('deposit_member_principal_payment_transaction_number', models.CharField(editable=False, max_length=255, unique=True)),
                ('deposit_member_principal_created_by', models.CharField(editable=False, max_length=255)),
                ('deposit_member_principal_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-deposit_member_principal_user_related',),
            },
        ),
        migrations.CreateModel(
            name='DepositProductMaster',
            fields=[
                ('deposit_product_master_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deposit_product_master_name', models.CharField(editable=False, max_length=255)),
                ('deposit_product_master_description', models.TextField(editable=False)),
                ('deposit_product_active', models.BooleanField(default=False)),
                ('deposit_product_master_revenue_share', models.DecimalField(decimal_places=4, editable=False, max_digits=6)),
                ('deposit_product_minimum_amount', models.DecimalField(decimal_places=12, default=0, editable=False, max_digits=30)),
                ('deposit_product_minimum_fluctuate_revenue', models.BooleanField(default=False)),
                ('deposit_product_master_created_by', models.CharField(editable=False, max_length=255)),
                ('deposit_product_master_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-deposit_product_master_created_date',),
            },
        ),
        migrations.AddIndex(
            model_name='depositproductmaster',
            index=models.Index(fields=['deposit_product_master_id'], name='deposits_de_deposit_eea5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='depositmemberprincipal',
            index=models.Index(fields=['deposit_member_principal_id', 'deposit_member_principal_user_related'], name='deposits_de_deposit_69c15b_idx'),
        ),
        migrations.AddIndex(
            model_name='depositmembermandatory',
            index=models.Index(fields=['deposit_member_mandatory_id', 'deposit_member_mandatory_user_related'], name='deposits_de_deposit_0342c3_idx'),
        ),
        migrations.AddIndex(
            model_name='depositmembercurrent',
            index=models.Index(fields=['deposit_member_current_id', 'deposit_member_current_user_related', 'deposit_member_current_transaction_related'], name='deposits_de_deposit_008486_idx'),
        ),
    ]
