# Generated by Django 3.1.5 on 2021-09-03 19:31

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDepositTimeTransit',
            fields=[
                ('transaction_deposit_time_transit_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_deposit_time_transit_user_related', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_time_transit_code', models.CharField(editable=False, max_length=255, unique=True)),
                ('transaction_deposit_time_transit_product_type', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_time_transit_amount', models.DecimalField(decimal_places=12, default=0, editable=False, max_digits=30)),
                ('transaction_deposit_time_transit_period_base', models.IntegerField(default=0, editable=False)),
                ('transaction_deposit_time_transit_type', models.CharField(editable=False, max_length=13)),
                ('transaction_deposit_time_revenue_share', models.DecimalField(decimal_places=4, editable=False, max_digits=6)),
                ('transaction_deposit_time_fluctuate_revenue', models.BooleanField(default=False)),
                ('transaction_deposit_time_transit_created_by', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_time_transit_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-transaction_deposit_time_transit_id',),
            },
        ),
        migrations.CreateModel(
            name='TransactionDepositTransit',
            fields=[
                ('transaction_deposit_transit_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_deposit_transit_user_related', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_transit_code', models.CharField(editable=False, max_length=255, unique=True)),
                ('transaction_deposit_transit_amount', models.DecimalField(decimal_places=12, editable=False, max_digits=30, null=True)),
                ('transaction_deposit_transit_unique_code_amount', models.DecimalField(decimal_places=12, editable=False, max_digits=30, null=True)),
                ('transaction_deposit_transit_gt_amount', models.DecimalField(decimal_places=12, editable=False, max_digits=30, null=True)),
                ('transaction_deposit_transit_type', models.CharField(editable=False, max_length=13)),
                ('transaction_deposit_transit_created_by', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_transit_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('transaction_deposit_transit_id',),
            },
        ),
        migrations.CreateModel(
            name='TransactionDepositVerified',
            fields=[
                ('transaction_deposit_verified_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_deposit_verified_user_related', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_verified_transit_code', models.CharField(editable=False, max_length=255, unique=True)),
                ('transaction_deposit_verified_status', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_verified_image_proof', models.TextField(null=True)),
                ('transaction_deposit_verified_image_proof_status', models.BooleanField(default=False)),
                ('transaction_deposit_verified_approval_status', models.BooleanField(default=False)),
                ('transaction_deposit_verified_created_by', models.CharField(editable=False, max_length=255)),
                ('transaction_deposit_verified_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_deposit_verified_created_by_admin', models.CharField(editable=False, max_length=255, null=True)),
                ('transaction_deposit_verified_created_date_admin', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ('-transaction_deposit_verified_id',),
            },
        ),
        migrations.AddIndex(
            model_name='transactiondepositverified',
            index=models.Index(fields=['transaction_deposit_verified_id', 'transaction_deposit_verified_user_related', 'transaction_deposit_verified_transit_code'], name='transaction_transac_d0b2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondeposittransit',
            index=models.Index(fields=['transaction_deposit_transit_id', 'transaction_deposit_transit_user_related'], name='transaction_transac_907d70_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondeposittimetransit',
            index=models.Index(fields=['transaction_deposit_time_transit_id', 'transaction_deposit_time_transit_user_related', 'transaction_deposit_time_transit_code'], name='transaction_transac_10881b_idx'),
        ),
    ]
