# Generated by Django 3.1.5 on 2021-09-03 19:31

import django.contrib.postgres.functions
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bank_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('bank_created_by', models.CharField(max_length=255)),
                ('bank_created_date', models.DateTimeField(auto_now_add=True)),
                ('bank_updated_by', models.CharField(max_length=255)),
                ('bank_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('bank_code',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('district_name', models.CharField(max_length=30)),
                ('district_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('district_created_by', models.CharField(max_length=255)),
                ('district_created_date', models.DateTimeField(auto_now_add=True)),
                ('district_updated_by', models.CharField(max_length=255)),
                ('district_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('district_name',),
            },
        ),
        migrations.CreateModel(
            name='LogNodeflux',
            fields=[
                ('log_nodeflux_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('log_nodeflux_job_id', models.CharField(max_length=255)),
                ('log_nodeflux_status', models.CharField(max_length=255)),
                ('log_nodeflux_analytic_type', models.CharField(max_length=255)),
                ('log_nodeflux_message', models.CharField(max_length=255)),
                ('log_nodeflux_ok', models.CharField(max_length=255)),
                ('log_nodeflux_produce', models.BooleanField(editable=False)),
                ('log_nodeflux_consume_status_job_id', models.CharField(max_length=255)),
                ('log_nodeflux_consume_status_status', models.CharField(max_length=255)),
                ('log_nodeflux_consume_status_analytic_type', models.CharField(max_length=255)),
                ('log_nodeflux_consume_status_message', models.CharField(max_length=255)),
                ('log_nodeflux_consume_status_ok', models.CharField(max_length=255)),
                ('log_nodeflux_consume_status_similarity', models.DecimalField(decimal_places=2, editable=False, max_digits=4, null=True)),
                ('log_nodeflux_consume_status', models.BooleanField(editable=False)),
                ('log_nodeflux_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-log_nodeflux_date',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('province_name', models.CharField(max_length=30)),
                ('province_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('province_created_by', models.CharField(max_length=255)),
                ('province_created_date', models.DateTimeField(auto_now_add=True)),
                ('province_updated_by', models.CharField(max_length=255)),
                ('province_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('province_name',),
            },
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('sub_district_id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sub_district_name', models.CharField(max_length=30)),
                ('sub_district_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('sub_district_created_by', models.CharField(max_length=255)),
                ('sub_district_created_date', models.DateTimeField(auto_now_add=True)),
                ('sub_district_updated_by', models.CharField(max_length=255)),
                ('sub_district_updated_at', models.DateTimeField(null=True)),
                ('sub_district_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.district')),
            ],
            options={
                'ordering': ('sub_district_name',),
            },
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['province_id', 'province_code'], name='utils_provi_provinc_1176f9_idx'),
        ),
        migrations.AddIndex(
            model_name='lognodeflux',
            index=models.Index(fields=['log_nodeflux_id', 'log_nodeflux_job_id'], name='utils_logno_log_nod_e53125_idx'),
        ),
        migrations.AddField(
            model_name='district',
            name='district_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.province'),
        ),
        migrations.AddIndex(
            model_name='banks',
            index=models.Index(fields=['bank_id', 'bank_code'], name='utils_banks_bank_id_337118_idx'),
        ),
        migrations.AddIndex(
            model_name='subdistrict',
            index=models.Index(fields=['sub_district_id', 'sub_district_relation', 'sub_district_code'], name='utils_subdi_sub_dis_e39ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['district_id', 'district_code', 'district_relation'], name='utils_distr_distric_b5c080_idx'),
        ),
    ]
