# Generated by Django 3.1.5 on 2021-06-22 05:19

import account.generator
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bank_id', models.CharField(default=account.generator.generator_uuid, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('bank_created_by', models.CharField(max_length=255)),
                ('bank_created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('bank_updated_by', models.CharField(max_length=255)),
                ('bank_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('bank_code',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.CharField(default=account.generator.generator_uuid, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('district_name', models.CharField(max_length=30)),
                ('district_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('district_created_by', models.CharField(max_length=255)),
                ('district_created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('district_updated_by', models.CharField(max_length=255)),
                ('district_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('district_name',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.CharField(default=account.generator.generator_uuid, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('province_name', models.CharField(max_length=30)),
                ('province_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('province_created_by', models.CharField(max_length=255)),
                ('province_created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('province_updated_by', models.CharField(max_length=255)),
                ('province_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('province_name',),
            },
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('sub_district_id', models.CharField(default=account.generator.generator_uuid, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('sub_district_name', models.CharField(max_length=30)),
                ('sub_district_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[1-9+]', 'Only digit characters.')])),
                ('sub_district_created_by', models.CharField(max_length=255)),
                ('sub_district_created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('sub_district_updated_by', models.CharField(max_length=255)),
                ('sub_district_updated_at', models.DateTimeField(null=True)),
                ('sub_district_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.district')),
            ],
            options={
                'ordering': ('sub_district_name',),
            },
        ),
        migrations.AddField(
            model_name='district',
            name='district_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.province'),
        ),
    ]
