version: '3.7'

services:
  web:
    build: .
    command: uvicorn asgi:app --debug --reload --port 5004 --host 0.0.0.0
    volumes:
      - ./fintech-transactional/:/usr/src/fintech-transactional/
    ports:
      - 5004:5004
#    networks:
#      - sample-network
#  redis:
#    image: redis
#    networks:
#      - sample-network
#
networks:
  default:
    name: sample-network