version: '3.7'

services:
  web:
    build: .
    command: uvicorn asgi:app --debug --reload --port 5003 --host 0.0.0.0
    volumes:
      - ./fintech-internal-admin/:/usr/src/fintech-internal-admin/
    ports:
      - 5003:5003
#    networks:
#      - sample-network
#  redis:
#    image: redis
#    networks:
#      - sample-network
#
networks:
  default:
    name: sample-network